In [1]:
import numpy as np
import pandas as pd


In [2]:
dataset = pd.read_csv('./Data.csv')

In [3]:
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [4]:
dataset.isna().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [5]:
X= dataset.iloc[: , :-1].values
y= dataset.iloc[: , -1: ].values

In [6]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X, y , test_size=0.2 , random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [8]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
y_train = sc.fit_transform(y_train)

In [9]:
y_train

array([[ 1.15069786],
       [ 0.79540777],
       [-1.30936356],
       ...,
       [ 0.27595724],
       [ 0.49346982],
       [-1.53508417]])

In [10]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(x_train , y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [11]:
y_pred = regressor.predict(x_test)

In [12]:
y_pred

array([-1.47997316,  0.02150856,  0.33751741, ...,  1.00588491,
       -0.96990323,  0.48350294])

In [13]:
y_pred = sc.inverse_transform(y_pred)
y_pred

array([429.06, 454.67, 460.06, ..., 471.46, 437.76, 462.55])

In [14]:
from sklearn.metrics import r2_score
print(f'The r2 score is : {r2_score(y_test , y_pred)}')

The r2 score is : 0.9211930894723408


In [15]:
#thank you